### ISSUE TITLE
Size is not defined error

### ISSUE THREAD

**Issue by joshbedo** [alinz/react-native-pure-icon#1]
I keep getting this error when i add the `<Icon />` tag. Does anyone know how i can fix it?

![](http://i.imgur.com/eWknxw2.jpg)

**Comment by alinz** [comment]
@joshbedo thanks for reporting that. I have fixed this issue and you should be able to see with new version pushed into npm!

cheers,

**Comment by joshbedo** [comment]
@alinz Yup also i noticed you're using `<Text />` but you're never importing it up at top.

**Comment by alinz** [comment]
@joshbedo good catch, This is a very simple project and I wanted to document how one can use custom icon in react-native. But, thanks for sharp eye!
:+1:
